apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.sle-bci.neuvector-demo-2
    namespace: neuvector-demo-2
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress: []
    process:
    - action: allow
      allow_update: false
      name: cat
      path: /usr/bin/cat
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: sh
      path: /usr/bin/bash
    - action: allow
      allow_update: false
      name: sleep
      path: /usr/bin/sleep
    process_profile:
      baseline: basic
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: sle-bci.neuvector-demo-2
        - key: domain
          op: =
          value: neuvector-demo-2
        name: nv.sle-bci.neuvector-demo-2
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
