apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    name: ns-neuvector-demo-2
    namespace: ""
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress: []
    process:
    - action: deny
      allow_update: false
      name: cat
      path: /usr/bin/cat
    target:
      policymode: N/A
      selector:
        comment: ""
        criteria:
        - key: namespace
          op: =
          value: neuvector-demo-2
        name: ns-neuvector-demo-2
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
