apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvWafSecurityRule
  metadata:
    name: sensor.injection
  spec:
    sensor:
      comment: to detect injection attempt
      name: sensor.injection
      rules:
      - name: Demarc
        patterns:
        - context: url
          key: pattern
          op: regex
          value: \/dm\/demarc
        - context: packet
          key: pattern
          op: regex
          value: s_key=
      - name: INDICATOR-OBFUSCATION
        patterns:
        - context: url
          key: pattern
          op: regex
          value: CHR\(.*CHR\(.*CHR\(.*CHR\(.*CHR\(
      - name: SQLSleepFunction
        patterns:
        - context: header
          key: pattern
          op: regex
          value: User-Agent\x3A\x20[^\r\n]*sleep\x28
      - name: WebVulnerabilityScanner
        patterns:
        - context: url
          key: pattern
          op: regex
          value: http:\/www.acunetix.com
        - context: header
          key: pattern
          op: regex
          value: Acunetix-
      - name: WebcenterFatWireSatellite
        patterns:
        - context: packet
          key: pattern
          op: regex
          value: blobheadername2=Location.*blobheadervalue2=
kind: List
metadata: null
