{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-demo
  labels:
    app: {{ .Release.Name }}-demo
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-demo
            port:
              number: 8080
        path: /
        pathType: Prefix
{{ end }}
